{"text": "2023-07-08T13:32:58.216528+0500 ERROR An error has been caught in function '<module>', process 'MainProcess' (8219), thread 'MainThread' (139776937607168):\nTraceback (most recent call last):\n\n> File \"/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py\", line 19, in <module>\n    main()\n    └ <function main at 0x7f2058c0bf40>\n\n  File \"/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py\", line 15, in main\n    divide(1, 0)\n    └ <function divide at 0x7f205aacfd90>\n\n  File \"/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py\", line 10, in divide\n    return a / b\n           │   └ 0\n           └ 1\n\nZeroDivisionError: division by zero\n", "record": {"elapsed": {"repr": "0:00:00.007927", "seconds": 0.007927}, "exception": {"type": "ZeroDivisionError", "value": "division by zero", "traceback": true}, "extra": {}, "file": {"name": "Автоматизация.py", "path": "/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py"}, "function": "<module>", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 19, "message": "An error has been caught in function '<module>', process 'MainProcess' (8219), thread 'MainThread' (139776937607168):", "module": "Автоматизация", "name": "__main__", "process": {"id": 8219, "name": "MainProcess"}, "thread": {"id": 139776937607168, "name": "MainThread"}, "time": {"repr": "2023-07-08 13:32:58.216528+05:00", "timestamp": 1688805178.216528}}}
{"text": "2023-07-08T14:00:15.521927+0500 ERROR An error has been caught in function '<module>', process 'MainProcess' (27130), thread 'MainThread' (140435176226816):\nTraceback (most recent call last):\n\n> File \"/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py\", line 19, in <module>\n    main()\n    └ <function main at 0x7fb99ad47f40>\n\n  File \"/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py\", line 15, in main\n    divide(1, 0)\n    └ <function divide at 0x7fb99bb63d90>\n\n  File \"/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py\", line 10, in divide\n    return a / b\n           │   └ 0\n           └ 1\n\nZeroDivisionError: division by zero\n", "record": {"elapsed": {"repr": "0:00:00.006784", "seconds": 0.006784}, "exception": {"type": "ZeroDivisionError", "value": "division by zero", "traceback": true}, "extra": {}, "file": {"name": "Автоматизация.py", "path": "/home/masavnik/PycharmProjects/basics_python/libraries/loguru/Автоматизация.py"}, "function": "<module>", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 19, "message": "An error has been caught in function '<module>', process 'MainProcess' (27130), thread 'MainThread' (140435176226816):", "module": "Автоматизация", "name": "__main__", "process": {"id": 27130, "name": "MainProcess"}, "thread": {"id": 140435176226816, "name": "MainThread"}, "time": {"repr": "2023-07-08 14:00:15.521927+05:00", "timestamp": 1688806815.521927}}}
